### ISSUE TITLE
configFactory not run on the create star-rating-comp

### ISSUE THREAD

**Issue by MohsenAra** [BioPhoton/angular-star-rating#43]
I Create Factory for StarRatingConfig class  like config sample and config it in  module
when inject StarRatingConfig  this exceute 
but when change asset path not  work 
-----------------------
i check the source 

in constructor of  star-rating.ts when want create instance of StarRatingConfig use 
config=new StarRatingConfig()
 but i think must be injected !!!
please guide me
thanks

**Comment by BioPhoton** [comment]
Hi @MohsenAra you are right. We have to inject it. At the time it was a first step to a configurable module. Because of heavy workload on other projects i did not finished it.

The goal would be to create a static forRoot method in your module class.
There under providers we have to place the StarRatingConfig service. We then are able to inject it into the constructor in star-rating.ts. 

A second step then would be to accept a param in the forRoot method which is the Obj or service with the custom settings. In the method we could merge these settings into a new service and provide it under StarRatingConfig. You could use the interface of StaRatingConfig to type your custom settings.

When i have a bit more time i will finish configurable module features. 
But i also would merge a earlier PR of your approach ;-)

Best Michael

**Comment by BioPhoton** [comment]
Fixed in latest version
