### ISSUE TITLE
Only ts files in the npm storage

### ISSUE THREAD

**Issue by aberezkin** [BioPhoton/angular-star-rating#7]
There are only `*.ts` files in npm storage which is not a good practice I think. It's better to put only compiled `*.js` files and ignore anything else with `.npmignore` file. 

Also, there is `node_modules` folder which should be ignored too.

**Comment by BioPhoton** [comment]
Hi @aberezkin! Thx for your Post!!

Im totally with you. Currently i don't have best practice experience in trems of lib bundling in ng2. To be ohnest, since I switched to webpack also my builds with ng1 are not satisfying. So any help is welcome!!

I will try to get more time on this topic and deliver something that is satisfying for me.

**Comment by aberezkin** [comment]
Here's the [post](http://blog.angular-university.io/how-to-create-an-angular-2-library-and-how-to-consume-it-jspm-vs-webpack/) that helped me to publish my first ng2 component library to npm.

**Comment by BioPhoton** [comment]
Hi @aberezkin, 

in the latest version are also js files and the related maps provided next to the ts files.

I used the yeoman angular2-library generator as i hope it will be updated frequently...

Feel free to reopen this issue if there is a need.
